version: '3.8'

services:
  django-app:
    image: python:3.12-slim
    container_name: django_app
    volumes:
      - ./app/django:/app
      - ./.env:/app/.env
    working_dir: /app
    env_file:
      - .env
    environment:
      - VIRTUAL_ENV=/app/.venv
      - PATH=/app/.venv/bin:$PATH
    ports:
      - "${DJANGO_LOCAL_PORT}:8000"
    command: >
      bash -c "apt-get update && apt-get install -y libpq-dev build-essential &&
      python -m venv .venv &&
      . .venv/bin/activate &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres:
        condition: service_healthy

  modeling-dev:
    image: python:3.12-slim
    container_name: modeling_dev
    volumes:
      - ./app/modeling:/app
      - ./.env:/app/.env
    working_dir: /app
    env_file:
      - .env
    # Don't automatically start with docker-compose up
    profiles: ["dev"]
    # Interactive mode for development
    stdin_open: true
    tty: true
    command: bash
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
    driver: local