# Generated by Django 5.2 on 2025-04-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirtyMinCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.ticker')),
            ],
            options={
                'verbose_name': '30-Minute Candle',
                'verbose_name_plural': '30-Minute Candles',
                'indexes': [models.Index(fields=['ticker', 'timestamp'], name='stocks_thir_ticker__b7736c_idx')],
                'unique_together': {('ticker', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='HourCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.ticker')),
            ],
            options={
                'verbose_name': 'Hour Candle',
                'verbose_name_plural': 'Hour Candles',
                'indexes': [models.Index(fields=['ticker', 'timestamp'], name='stocks_hour_ticker__d0bf4a_idx')],
                'unique_together': {('ticker', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='FiveMinCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.ticker')),
            ],
            options={
                'verbose_name': '5-Minute Candle',
                'verbose_name_plural': '5-Minute Candles',
                'indexes': [models.Index(fields=['ticker', 'timestamp'], name='stocks_five_ticker__0781c8_idx')],
                'unique_together': {('ticker', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='DailyCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.ticker')),
            ],
            options={
                'verbose_name': 'Daily Candle',
                'verbose_name_plural': 'Daily Candles',
                'indexes': [models.Index(fields=['ticker', 'timestamp'], name='stocks_dail_ticker__6b9b1e_idx')],
                'unique_together': {('ticker', 'timestamp')},
            },
        ),
    ]
