# Generated by Django 5.0.2 on 2025-04-26 18:10

import stocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycandle',
            name='id',
            field=models.UUIDField(db_default=stocks.models.RandomUUID(), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fivemincandle',
            name='id',
            field=models.UUIDField(db_default=stocks.models.RandomUUID(), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hourcandle',
            name='id',
            field=models.UUIDField(db_default=stocks.models.RandomUUID(), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thirtymincandle',
            name='id',
            field=models.UUIDField(db_default=stocks.models.RandomUUID(), editable=False, primary_key=True, serialize=False),
        ),
    ]
