# Generated by Django 5.0.2 on 2025-04-26 18:37

import stocks.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_dailycandle_id_alter_fivemincandle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycandle',
            name='timestamp',
            field=stocks.models.DateTimeWithoutTZField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fivemincandle',
            name='timestamp',
            field=stocks.models.DateTimeWithoutTZField(db_index=True),
        ),
        migrations.AlterField(
            model_name='hourcandle',
            name='timestamp',
            field=stocks.models.DateTimeWithoutTZField(db_index=True),
        ),
        migrations.AlterField(
            model_name='thirtymincandle',
            name='timestamp',
            field=stocks.models.DateTimeWithoutTZField(db_index=True),
        ),
    ]
